spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.98.219.27:3306/guyunwenchuang?characterEncoding=UTF-8&useSSL=true&&serverTimezone=Asia/Shanghai
    username: root
    password: 27564138
    hikari:
      minimum-idle: 3
      maximum-pool-size: 5
      connection-test-query: SELECT 1