server:
  port: 9000
spring:
  application:
    name: boot-server
  profiles:
    active: dev
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mini-program:
  user:
    appid: wx045ddd6290468a53
    secret: 906e74da16c319b7f7a9768d1c5ec640
  doctor:
    appid: wxbcb506cbd018cd24
    secret: 1327e89037a3ee04c1ddb9b54f9ae803
management:
  health:
    redis:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
