spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.98.219.27:3306/medical_care?characterEncoding=UTF-8&useSSL=true&&serverTimezone=Asia/Shanghai
    username: root
    password: 27564138
    hikari:
      minimum-idle: 3
      maximum-pool-size: 5
      connection-test-query: SELECT 1
redis:
  database:
    auth: 2
  host: localhost
  port: 6379
  password: lncqekZ0Nk
  timeout: 1000
  pool:
    max-active: 100
    max-idle: 3
    min-idle: 0
    max-wait: -1
file:
  image:
    url-mapping: /image/
    store-path: /app/medicalCare/image/